### ISSUE TITLE
Spendable income calculation is weirdly wrong

### ISSUE THREAD

**Issue by vjcortesa** [averbraeck/housinggame-player#54] opened 2024-04-06 12:23 UTC
- [ ] The spendable income is calculated wrong from round 1 for two of the three players of this testing session that I was running to recreate the bug of the IHE-Delft session:
t2p5 (IHE-Delft): t1p1 (Test) -> U10 (R1: Sand bags)
t2p4 (IHE-Delft): t1p2 (Test) -> N07, I cound not retrieve from the facilitator side where was that player living at the IHE-Delft round 1
t2p6 (IHE-Delft): t1p6 (Test) -> U04 (R1: Green garden and rise level)
- [ ] The error was not present when testing the player alone
- [ ] The error appears when trying to buy improvements
- [ ] At last, the website broke when I advanced the game steps with some of the players not all on the table, upon approval from the facilitator. When I tried to continue with this player, instead of a warning the website broke up  
![240224_Test session errors](https://github.com/averbraeck/housinggame-player/assets/8215750/98de26ae-c25f-48d3-af3b-aec06e8d64ac)
![240224_t1p2_spendable income bug](https://github.com/averbraeck/housinggame-player/assets/8215750/59396f0b-b5aa-4555-b89b-1f11eb3c6d7c)

**Comment by averbraeck** [comment] 2024-04-08 03:29
@vjcortesa : Question: did you run the different players at the same time on the same computer in different tabs / screens of the browser? If so, the results of the players can get mixed and overwritten. Only one player should play at a given time on a computer. 

If not, I will have to try to reproduce the error.

**Comment by vjcortesa** [comment] 2024-04-08 03:43
Dear Alexander, I got this error by playing two players in different browsers (one in chrome, one in explorer) and one player on my phone (Test t1p2) was on my phone and was wrong

**Comment by averbraeck** [comment] 2024-04-08 04:09
Strange. I have not been able to reproduce any error like this. The bottom left player looks as if there was a timeout. When I log in as t1p1 in that session now, I get normal screens:

![image](https://github.com/averbraeck/housinggame-player/assets/13779793/e947b4c5-60c2-467d-b42d-233747feab2e)


The wrong calculation at the bottom right is because it is incomplete -- the taxes, mortgage, and bought measures are missing. I will repair that.

The two screens in the top row have a difference of 20k. That is indeed strange, and looks as if the taxes have been deducted twice. I looked in the database, and also there the calculation wold end up being 20 k more positive. Did you do something special with the players in the test session, e.g., advancing the facilitator far ahead of the player, like closing the buying and then buying afterward? Or did everything go normal?

**Comment by averbraeck** [comment] 2024-09-28 14:13
The income looks correct in the last sessions that were played, and the calculation that is shown on the screen in the Budget tab is complete.

**Closed by averbraeck** 2024-09-28 14:13 UTC
Labels: bug, question
